apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system  # This is the namespace of the actual pods, NOT the flux resource
spec:
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: cilium
    namespace: flux-system
  values:
    ipam:
      mode: "cluster-pool"
      operator:
        clusterPoolIPv4PodCIDRList: ["11.1.0.0/16"]
    hubble:
      enabled: true
      relay:
        enabled: true
      ui:
        enabled: true
      metrics:
        enabled: [dns, drop, tcp, flow, icmp, http]
        serviceMonitor:
          enabled: false
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: false
    operator:
      replicas: 1
      prometheus:
        enabled: true
        serviceMonitor:
          enabled: false

    bpf:
      masquerade: true

    kubeProxyReplacement: true
    k8sServiceHost: 127.0.0.1
    k8sServicePort: 6443
